name: 'Four Keys Creation'

on:
  workflow_dispatch:

jobs:
  deploy-four-keys:
    name: 'Deploy Four Keys'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./setup

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      
    - name: Four Keys creation
      env: 
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: ./setup_customization.sh

    # On push to main, build or change infrastructure according to Terraform configuration files
    #- name: Terraform Apply
    #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #  run: terraform apply -auto-approve
