name: 'Four Keys Create'

on:
  workflow_dispatch:

jobs:
  deploy-four-keys:
    name: 'Deploy Four Keys'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: us-east1
      TF_VAR_bigquery_region: US
      TF_VAR_parsers: '["github"]'
      TF_VAR_backend_bucket: shadamn-4keys-terraform-state

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init
      
    - name: Four Keys creation
      run: terraform apply -auto-approve

    # On push to main, build or change infrastructure according to Terraform configuration files
    #- name: Terraform Apply
    #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #  run: terraform apply -auto-approve
