name: 'Four Keys Validation'

on:
  workflow_dispatch:

jobs:
  four-keys-validation:
    name: 'Validation'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    env:
      FOURKEYS_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      FOURKEYS_REGION: us-east1
      BIGQUERY_REGION: US
      GIT_SYSTEM: github
      TF_BACKEND_BUCKET: shadamn-4keys-terraform-state

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Create terraform.tfvars
      run: ./set_terraform_vars.sh
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
