name: 'Four Keys Destroy'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: '4 Keys Destroy'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./setup

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Create Terraform variable file
      run: |
           cat > terraform.tfvars <<EOF
           google_project_id = "ace-connection-329015"
           google_region = "us-east1"
           bigquery_region = "US"
           parsers = ["github"]
           EOF
           
    - name: Terraform init
      run: terraform init

    # Generates an execution plan for Terraform destroy
    - name: Terraform Plan Destroy
      run: terraform plan -destroy
    
    #- name: Terraform Destroy
    #  working-directory: ./setup
    #  run: terraform destroy -auto-approve
