name: 'Four Keys Validation'

on:
  workflow_dispatch:

jobs:
  four-keys-validation:
    name: 'Validation'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./setup

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Create terraform.tfvars
      env: 
        BIGQUERY_REGION: US
        FOURKEYS_REGION: us-east1
        FOURKEYS_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        GIT_SYSTEM: github
      run: ./set_terraform_vars.sh
    
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
